'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ADTools.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property app() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("app", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property computer() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("computer", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property computer_blocked() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_blocked", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property computer_expired() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_expired", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property computer_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property contact() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("contact", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property contact_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contact_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property container() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("container", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property container_unknown() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("container_unknown", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Objects.
        '''</summary>
        Public ReadOnly Property ctlGroupMember_lbl_Objects() As String
            Get
                Return ResourceManager.GetString("ctlGroupMember_lbl_Objects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Objects.
        '''</summary>
        Public ReadOnly Property ctlGroupMember_lbl_ObjectsList() As String
            Get
                Return ResourceManager.GetString("ctlGroupMember_lbl_ObjectsList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Selected objects.
        '''</summary>
        Public ReadOnly Property ctlGroupMember_lbl_SelectedObjects() As String
            Get
                Return ResourceManager.GetString("ctlGroupMember_lbl_SelectedObjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на From another domain you can not!.
        '''</summary>
        Public ReadOnly Property ctlGroupMember_msg_AnotherDomain() As String
            Get
                Return ResourceManager.GetString("ctlGroupMember_msg_AnotherDomain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Whatareyoudoing :(.
        '''</summary>
        Public ReadOnly Property ctlGroupMember_msg_AnotherDomainTitle() As String
            Get
                Return ResourceManager.GetString("ctlGroupMember_msg_AnotherDomainTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Groups.
        '''</summary>
        Public ReadOnly Property ctlGroupMemberOf_lbl_Groups() As String
            Get
                Return ResourceManager.GetString("ctlGroupMemberOf_lbl_Groups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Groups.
        '''</summary>
        Public ReadOnly Property ctlGroupMemberOf_lbl_GroupsList() As String
            Get
                Return ResourceManager.GetString("ctlGroupMemberOf_lbl_GroupsList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Selected groups.
        '''</summary>
        Public ReadOnly Property ctlGroupMemberOf_lbl_SelectedGroups() As String
            Get
                Return ResourceManager.GetString("ctlGroupMemberOf_lbl_SelectedGroups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt; Add.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_Add() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Change.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_Change() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_Change", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Email address.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_EmailAddress() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_EmailAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Hide.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_HiddenHide() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_HiddenHide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Show.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_HiddenShow() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_HiddenShow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Show/hide the address in the address book.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_HiddenToolTip() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_HiddenToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Quotas....
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_Quotas() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_Quotas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Remove &gt;.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_Remove() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_Remove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Exchange Server.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_Server() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Set primary.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_SetPrimary() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_SetPrimary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Share....
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_Share() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_Share", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на busy:.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_SizeBusy() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_SizeBusy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на quota:.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_SizeQuota() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_SizeQuota", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Connection state: .
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_State() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_State", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Shared.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_TypeShared() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_TypeShared", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Convert mailbox to user/shared.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_TypeToolTip() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_TypeToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на User.
        '''</summary>
        Public ReadOnly Property ctlMailbox_lbl_TypeUser() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_lbl_TypeUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Connection error.
        '''</summary>
        Public ReadOnly Property ctlMailbox_msg_ConnectionError() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_msg_ConnectionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Removing the primary address means completely removing the mailbox
        '''
        '''Are you sure?.
        '''</summary>
        Public ReadOnly Property ctlMailbox_msg_RemovingPrimaryAddress() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_msg_RemovingPrimaryAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Remove mailbox.
        '''</summary>
        Public ReadOnly Property ctlMailbox_msg_RemovingPrimaryAddressTitle() As String
            Get
                Return ResourceManager.GetString("ctlMailbox_msg_RemovingPrimaryAddressTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Availability (ICMP):.
        '''</summary>
        Public ReadOnly Property ctlNetwork_lbl_NetworkAvailabilityICMP() As String
            Get
                Return ResourceManager.GetString("ctlNetwork_lbl_NetworkAvailabilityICMP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Availability (TCP):.
        '''</summary>
        Public ReadOnly Property ctlNetwork_lbl_NetworkAvailabilityTCP() As String
            Get
                Return ResourceManager.GetString("ctlNetwork_lbl_NetworkAvailabilityTCP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Trace route:.
        '''</summary>
        Public ReadOnly Property ctlNetwork_lbl_NetworkTraceRoute() As String
            Get
                Return ResourceManager.GetString("ctlNetwork_lbl_NetworkTraceRoute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Unknown address.
        '''</summary>
        Public ReadOnly Property ctlNetwork_msg_AddressUnknown() As String
            Get
                Return ResourceManager.GetString("ctlNetwork_msg_AddressUnknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Available.
        '''</summary>
        Public ReadOnly Property ctlNetwork_msg_Available() As String
            Get
                Return ResourceManager.GetString("ctlNetwork_msg_Available", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Not available.
        '''</summary>
        Public ReadOnly Property ctlNetwork_msg_NotAvailable() As String
            Get
                Return ResourceManager.GetString("ctlNetwork_msg_NotAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Reply from .
        '''</summary>
        Public ReadOnly Property ctlNetwork_msg_ReplyFrom() As String
            Get
                Return ResourceManager.GetString("ctlNetwork_msg_ReplyFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Unknown.
        '''</summary>
        Public ReadOnly Property ctlNetwork_msg_Unknown() As String
            Get
                Return ResourceManager.GetString("ctlNetwork_msg_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Copy.
        '''</summary>
        Public ReadOnly Property ctlObjectAttributes_ctxmnuCopy() As String
            Get
                Return ResourceManager.GetString("ctlObjectAttributes_ctxmnuCopy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Copy values.
        '''</summary>
        Public ReadOnly Property ctlObjectAttributes_ctxmnuCopyValues() As String
            Get
                Return ResourceManager.GetString("ctlObjectAttributes_ctxmnuCopyValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на All.
        '''</summary>
        Public ReadOnly Property ctlObjectAttributes_lbl_All() As String
            Get
                Return ResourceManager.GetString("ctlObjectAttributes_lbl_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Attribute.
        '''</summary>
        Public ReadOnly Property ctlObjectAttributes_lbl_Attribute() As String
            Get
                Return ResourceManager.GetString("ctlObjectAttributes_lbl_Attribute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Changed.
        '''</summary>
        Public ReadOnly Property ctlObjectAttributes_lbl_Changed() As String
            Get
                Return ResourceManager.GetString("ctlObjectAttributes_lbl_Changed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на New value.
        '''</summary>
        Public ReadOnly Property ctlObjectAttributes_lbl_NewValue() As String
            Get
                Return ResourceManager.GetString("ctlObjectAttributes_lbl_NewValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Value.
        '''</summary>
        Public ReadOnly Property ctlObjectAttributes_lbl_Value() As String
            Get
                Return ResourceManager.GetString("ctlObjectAttributes_lbl_Value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на With value.
        '''</summary>
        Public ReadOnly Property ctlObjectAttributes_lbl_WithValue() As String
            Get
                Return ResourceManager.GetString("ctlObjectAttributes_lbl_WithValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property domain() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("domain", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property domain_folder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("domain_folder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property favorite_folder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("favorite_folder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property filter_folder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("filter_folder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property group() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("group", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property group_distribution() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("group_distribution", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property group_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("group_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Objects:.
        '''</summary>
        Public ReadOnly Property lbl_Objects() As String
            Get
                Return ResourceManager.GetString("lbl_Objects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Selected: .
        '''</summary>
        Public ReadOnly Property lbl_ObjectsSelected() As String
            Get
                Return ResourceManager.GetString("lbl_ObjectsSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Objects: .
        '''</summary>
        Public ReadOnly Property lbl_ObjectsTotal() As String
            Get
                Return ResourceManager.GetString("lbl_ObjectsTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property network_folder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("network_folder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property object_unknown() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("object_unknown", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property organizationalunit() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("organizationalunit", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property properties() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("properties", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property ready() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ready", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property splash1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splash1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property user() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property user_blocked() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("user_blocked", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property user_expired() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("user_expired", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property user_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        '''</summary>
        Public ReadOnly Property warning() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Close window on create.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_CloseWindowOnCreate() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_CloseWindowOnCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Computer.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_Computer() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_Computer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Contact.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_Contact() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_Contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Container.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_Container() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_Container", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Create.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_Create() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_Create", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Create object.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_CreateObject() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_CreateObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Display name.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_DisplayName() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_DisplayName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Domain.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_Domain() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_Domain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Group.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_Group() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_Group", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Group scope.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_GroupScope() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_GroupScope", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Domain local.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_GroupScopeDomainLocal() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_GroupScopeDomainLocal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Global.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_GroupScopeGlobal() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_GroupScopeGlobal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Universal.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_GroupScopeUniversal() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_GroupScopeUniversal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Group type.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_GroupType() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_GroupType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Distribution.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_GroupTypeDistribution() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_GroupTypeDistribution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Security.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_GroupTypeSecurity() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_GroupTypeSecurity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Object (CN).
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_ObjectName() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_ObjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Open object.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_OpenObject() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_OpenObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Organizational unit.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_OrganizationalUnit() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_OrganizationalUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Logon name (pre-Windows 2000).
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_SAMAccountName() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_SAMAccountName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на shared mailbox.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_SharedMailbox() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_SharedMailbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на User.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_User() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Logon name.
        '''</summary>
        Public ReadOnly Property wndCreateObject_lbl_UserPrincipalName() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_lbl_UserPrincipalName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Default password is not set.
        '''</summary>
        Public ReadOnly Property wndCreateObject_msg_DefaultPasswordIsNotSet() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_msg_DefaultPasswordIsNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Missed required fields.
        '''</summary>
        Public ReadOnly Property wndCreateObject_msg_MissedRequiredFields() As String
            Get
                Return ResourceManager.GetString("wndCreateObject_msg_MissedRequiredFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Domain browser.
        '''</summary>
        Public ReadOnly Property wndDomainBrowser_lbl_DomainBrowser() As String
            Get
                Return ResourceManager.GetString("wndDomainBrowser_lbl_DomainBrowser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на OK.
        '''</summary>
        Public ReadOnly Property wndDomainBrowser_lbl_OK() As String
            Get
                Return ResourceManager.GetString("wndDomainBrowser_lbl_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Domains.
        '''</summary>
        Public ReadOnly Property wndDomains() As String
            Get
                Return ResourceManager.GetString("wndDomains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Add.
        '''</summary>
        Public ReadOnly Property wndDomains_btnDomainsAdd() As String
            Get
                Return ResourceManager.GetString("wndDomains_btnDomainsAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Remove.
        '''</summary>
        Public ReadOnly Property wndDomains_btnDomainsRemove() As String
            Get
                Return ResourceManager.GetString("wndDomains_btnDomainsRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Name.
        '''</summary>
        Public ReadOnly Property wndDomains_dgPatternTelephoneNumbers1() As String
            Get
                Return ResourceManager.GetString("wndDomains_dgPatternTelephoneNumbers1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Pattern.
        '''</summary>
        Public ReadOnly Property wndDomains_dgPatternTelephoneNumbers2() As String
            Get
                Return ResourceManager.GetString("wndDomains_dgPatternTelephoneNumbers2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Range.
        '''</summary>
        Public ReadOnly Property wndDomains_dgPatternTelephoneNumbers3() As String
            Get
                Return ResourceManager.GetString("wndDomains_dgPatternTelephoneNumbers3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Connect.
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_Connect() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_Connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Domain name.
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_DomainName() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_DomainName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Password.
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_Password() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Computer (list or comma-separated).
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_Patterns_Computer() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_Patterns_Computer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Default password.
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_Patterns_DefaultPassword() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_Patterns_DefaultPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на A template for naming a mailbox in the handlebars format (see the &quot;Templates&quot; tab).
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_Patterns_Exchange() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_Patterns_Exchange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Phone numbers.
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_Patterns_PhoneNumbers() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_Patterns_PhoneNumbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Username (list or comma-separated).
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_Patterns_Username() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_Patterns_Username", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на For example:.
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_PatternsExample() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_PatternsExample", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на user-{{n}} = user-1 / user-2 / user-3 / user-100.
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_PatternsExampleDef() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_PatternsExampleDef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на The variables used are:
        '''{{n}} - number;
        '''{{displayname}} - display name;
        '''
        '''Used functions:
        '''{{lz number data}} - add (number) leading zeros to (data)
        '''{{lz 5 n}} = 00777
        '''
        '''{{fst number data}} - take the first (number) characters (data)
        '''{{fst 3 displayname}} = Arn    [old Alois Schwarzenegger]
        '''
        '''{{trans data}} - transliteration into the Latin alphabet
        '''{{trans displayname}} = ivanov ivan ivanovich
        '''
        '''{{split 2 displayname}} = Alois
        '''
        '''Combinations:
        '''{{fst 1 (trans (split 1 displayname))}}. {{trans (spli [остаток строки не уместился]&quot;;.
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_PatternsExampleDefinition() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_PatternsExampleDefinition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Handlebars.
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_PatternsExampleDefinitionHandlebars() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_PatternsExampleDefinitionHandlebars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Search root.
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_SearchRoot() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_SearchRoot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Username.
        '''</summary>
        Public ReadOnly Property wndDomains_lbl_Username() As String
            Get
                Return ResourceManager.GetString("wndDomains_lbl_Username", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Property.
        '''</summary>
        Public ReadOnly Property wndDomains_lvDomainProperties1() As String
            Get
                Return ResourceManager.GetString("wndDomains_lvDomainProperties1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Value.
        '''</summary>
        Public ReadOnly Property wndDomains_lvDomainProperties2() As String
            Get
                Return ResourceManager.GetString("wndDomains_lvDomainProperties2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Exchange.
        '''</summary>
        Public ReadOnly Property wndDomains_tabctlDomain_Exchange() As String
            Get
                Return ResourceManager.GetString("wndDomains_tabctlDomain_Exchange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Groups.
        '''</summary>
        Public ReadOnly Property wndDomains_tabctlDomain_Groups() As String
            Get
                Return ResourceManager.GetString("wndDomains_tabctlDomain_Groups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Patterns.
        '''</summary>
        Public ReadOnly Property wndDomains_tabctlDomain_Patterns() As String
            Get
                Return ResourceManager.GetString("wndDomains_tabctlDomain_Patterns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Domain.
        '''</summary>
        Public ReadOnly Property wndDomains_tabctlDomain1() As String
            Get
                Return ResourceManager.GetString("wndDomains_tabctlDomain1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Search root.
        '''</summary>
        Public ReadOnly Property wndDomains_tabctlDomain2() As String
            Get
                Return ResourceManager.GetString("wndDomains_tabctlDomain2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на If your organization uses Microsoft Exchange Server, specify the Exchange server name and mail domain list.
        '''This information is used to manage users&apos; mailboxes using PowerShell. .
        '''</summary>
        Public ReadOnly Property wndDomains_txt_Exchange() As String
            Get
                Return ResourceManager.GetString("wndDomains_txt_Exchange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Select the standard domain security groups.
        '''The created users will be automatically added as the group member. .
        '''</summary>
        Public ReadOnly Property wndDomains_txt_Groups() As String
            Get
                Return ResourceManager.GetString("wndDomains_txt_Groups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Specify the format for naming objects in the handlebars format, specifying the arguments in double curly braces, where the arguments are:
        '''{{n}} - number;
        '''{{displayname}} - display name;.
        '''</summary>
        Public ReadOnly Property wndDomains_txt_Patterns() As String
            Get
                Return ResourceManager.GetString("wndDomains_txt_Patterns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на In the next field, you must specify (select) the container in which the objects will be searched.
        '''
        '''In most cases, user objects are located in a specific container. Searching in such a container will shorten the search time.
        '''
        '''However, you can also specify the root of the domain as the root of the search..
        '''</summary>
        Public ReadOnly Property wndDomains_txt_SearchRoot() As String
            Get
                Return ResourceManager.GetString("wndDomains_txt_SearchRoot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Use Exchange Server.
        '''</summary>
        Public ReadOnly Property wndDomains_txt_UseExchange() As String
            Get
                Return ResourceManager.GetString("wndDomains_txt_UseExchange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Copy.
        '''</summary>
        Public ReadOnly Property wndErrorLog_ctxmnuErrorCopy() As String
            Get
                Return ResourceManager.GetString("wndErrorLog_ctxmnuErrorCopy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Debug.
        '''</summary>
        Public ReadOnly Property wndErrorLog_lbl_Debug() As String
            Get
                Return ResourceManager.GetString("wndErrorLog_lbl_Debug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Exception.
        '''</summary>
        Public ReadOnly Property wndErrorLog_lbl_Exception() As String
            Get
                Return ResourceManager.GetString("wndErrorLog_lbl_Exception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Time.
        '''</summary>
        Public ReadOnly Property wndErrorLog_lbl_Timestamp() As String
            Get
                Return ResourceManager.GetString("wndErrorLog_lbl_Timestamp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Clone window.
        '''</summary>
        Public ReadOnly Property wndMain_btnWindowClone() As String
            Get
                Return ResourceManager.GetString("wndMain_btnWindowClone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Add to favorites.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsAddToFavorites() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsAddToFavorites", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Copy.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsCopy() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsCopy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Create object....
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsCreateObject() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsCreateObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Cut.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsCut() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsCut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Disable/Enable.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsDisableEnable() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsDisableEnable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Set expiration date to midnight....
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsExpirationDate() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsExpirationDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на External software.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsExternalSoftware() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsExternalSoftware", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Object location.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsOpenObjectLocation() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsOpenObjectLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Paste.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsPaste() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsPaste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Properties....
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsProperties() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Remove.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsRemove() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Rename....
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsRename() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsRename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Reset password to default.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsResetPassword() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsResetPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Select all.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnuObjectsSelectAll() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnuObjectsSelectAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Add to favorites.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnutviDomainsAddToFavorites() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnutviDomainsAddToFavorites", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Copy.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnutviDomainsCopy() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnutviDomainsCopy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Create object....
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnutviDomainsCreateObject() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnutviDomainsCreateObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Cut.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnutviDomainsCut() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnutviDomainsCut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Paste.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnutviDomainsPaste() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnutviDomainsPaste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Properties....
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnutviDomainsProperties() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnutviDomainsProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Delete.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnutviDomainsRemove() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnutviDomainsRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Rename....
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnutviDomainsRename() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnutviDomainsRename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Object location.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnutviFavoritesOpenObjectLocation() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnutviFavoritesOpenObjectLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Properties....
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnutviFavoritesProperties() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnutviFavoritesProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Remove from favorites.
        '''</summary>
        Public ReadOnly Property wndMain_ctxmnutviFavoritesRemoveFromFavorites() As String
            Get
                Return ResourceManager.GetString("wndMain_ctxmnutviFavoritesRemoveFromFavorites", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Filter.
        '''</summary>
        Public ReadOnly Property wndMain_lbl_SearchFilter() As String
            Get
                Return ResourceManager.GetString("wndMain_lbl_SearchFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Search results:.
        '''</summary>
        Public ReadOnly Property wndMain_lbl_SearchResults() As String
            Get
                Return ResourceManager.GetString("wndMain_lbl_SearchResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Edit.
        '''</summary>
        Public ReadOnly Property wndMain_mnuEdit() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Create object ....
        '''</summary>
        Public ReadOnly Property wndMain_mnuEdit_CreateObject() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuEdit_CreateObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на File.
        '''</summary>
        Public ReadOnly Property wndMain_mnuFile() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Exit.
        '''</summary>
        Public ReadOnly Property wndMain_mnuFile_Exit() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuFile_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Print.
        '''</summary>
        Public ReadOnly Property wndMain_mnuFile_Print() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuFile_Print", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Help.
        '''</summary>
        Public ReadOnly Property wndMain_mnuHelp() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на About ....
        '''</summary>
        Public ReadOnly Property wndMain_mnuHelp_About() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuHelp_About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Search.
        '''</summary>
        Public ReadOnly Property wndMain_mnuSearch() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Domains.
        '''</summary>
        Public ReadOnly Property wndMain_mnuSearchDomains() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuSearchDomains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Mode.
        '''</summary>
        Public ReadOnly Property wndMain_mnuSearchMode() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuSearchMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Advanced.
        '''</summary>
        Public ReadOnly Property wndMain_mnuSearchMode_Advanced() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuSearchMode_Advanced", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Default.
        '''</summary>
        Public ReadOnly Property wndMain_mnuSearchMode_Default() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuSearchMode_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Classes.
        '''</summary>
        Public ReadOnly Property wndMain_mnuSearchObjectClasses() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuSearchObjectClasses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Save current filter ....
        '''</summary>
        Public ReadOnly Property wndMain_mnuSearchSaveCurrentFilter() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuSearchSaveCurrentFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Service.
        '''</summary>
        Public ReadOnly Property wndMain_mnuService() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Domain options ....
        '''</summary>
        Public ReadOnly Property wndMain_mnuService_DomainOptions() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuService_DomainOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Error log ....
        '''</summary>
        Public ReadOnly Property wndMain_mnuService_ErrorLog() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuService_ErrorLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Log ....
        '''</summary>
        Public ReadOnly Property wndMain_mnuService_Log() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuService_Log", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Preferences ....
        '''</summary>
        Public ReadOnly Property wndMain_mnuService_Preferences() As String
            Get
                Return ResourceManager.GetString("wndMain_mnuService_Preferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Are you sure?.
        '''</summary>
        Public ReadOnly Property wndMain_msg_AreYouSure() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_AreYouSure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Current filter is empty..
        '''</summary>
        Public ReadOnly Property wndMain_msg_CannotSaveCurrentFilter() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_CannotSaveCurrentFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Copy object.
        '''</summary>
        Public ReadOnly Property wndMain_msg_CopyObject() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_CopyObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Within a domain, you can copy only one object.
        '''</summary>
        Public ReadOnly Property wndMain_msg_CopyOneObjectWithinDomain() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_CopyOneObjectWithinDomain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Enter new filter name:.
        '''</summary>
        Public ReadOnly Property wndMain_msg_EnterFilterName() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_EnterFilterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Enter object name:.
        '''</summary>
        Public ReadOnly Property wndMain_msg_EnterObjectName() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_EnterObjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Move object.
        '''</summary>
        Public ReadOnly Property wndMain_msg_MoveObject() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_MoveObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Move:
        '''{0}
        '''
        '''To container:
        '''{1}.
        '''</summary>
        Public ReadOnly Property wndMain_msg_MoveObjectToContainer() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_MoveObjectToContainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Moving to another domain is prohibited.
        '''</summary>
        Public ReadOnly Property wndMain_msg_MovingIsProhibited() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_MovingIsProhibited", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на {0} objects.
        '''</summary>
        Public ReadOnly Property wndMain_msg_NObjects() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_NObjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Unknown class of the object to be copied.
        '''</summary>
        Public ReadOnly Property wndMain_msg_ObjectUnknownClass() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_ObjectUnknownClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Paste object.
        '''</summary>
        Public ReadOnly Property wndMain_msg_PasteObject() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_PasteObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Remove object.
        '''</summary>
        Public ReadOnly Property wndMain_msg_RemoveObject() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_RemoveObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Rename object.
        '''</summary>
        Public ReadOnly Property wndMain_msg_RenameObject() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_RenameObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на This is Organizational Unit!.
        '''</summary>
        Public ReadOnly Property wndMain_msg_ThisIsOrganizationaUnit() As String
            Get
                Return ResourceManager.GetString("wndMain_msg_ThisIsOrganizationaUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Domains.
        '''</summary>
        Public ReadOnly Property wndMain_tviDomains() As String
            Get
                Return ResourceManager.GetString("wndMain_tviDomains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Favorites.
        '''</summary>
        Public ReadOnly Property wndMain_tviFavorites() As String
            Get
                Return ResourceManager.GetString("wndMain_tviFavorites", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Filters.
        '''</summary>
        Public ReadOnly Property wndMain_tviFilters() As String
            Get
                Return ResourceManager.GetString("wndMain_tviFilters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Remove filter.
        '''</summary>
        Public ReadOnly Property wndMain_tviFiltersRemoveFromFilters() As String
            Get
                Return ResourceManager.GetString("wndMain_tviFiltersRemoveFromFilters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Initials.
        '''</summary>
        Public ReadOnly Property wndObject_Initials() As String
            Get
                Return ResourceManager.GetString("wndObject_Initials", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на All attributes.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_AllAttributes() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_AllAttributes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Basic information.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_BasicInformation() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_BasicInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Company.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Company() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Company", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Department.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Department() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Department", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Description.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Description() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Display:.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Display() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Display", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Display name.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_DisplayName() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_DisplayName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на DNS-name.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_DNSName() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_DNSName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Account name.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_EventAccountName() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_EventAccountName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на All.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_EventAll() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_EventAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Category.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_EventCategory() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_EventCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Code.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_EventCode() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_EventCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Failure.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_EventFailure() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_EventFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Logon type.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_EventLogonType() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_EventLogonType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Source address.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_EventSourceAddress() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_EventSourceAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Success.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_EventSuccess() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_EventSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Time.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_EventTimeGenerated() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_EventTimeGenerated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Exchange.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Exchange() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Exchange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Given name.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_GivenName() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_GivenName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Group scope.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_GroupScope() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_GroupScope", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Domain local.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_GroupScopeDomainLocal() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_GroupScopeDomainLocal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Global.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_GroupScopeGlobal() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_GroupScopeGlobal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Universal.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_GroupScopeUniversal() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_GroupScopeUniversal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Group type.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_GroupType() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_GroupType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Distribution.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_GroupTypeDistribution() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_GroupTypeDistribution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Security.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_GroupTypeSecurity() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_GroupTypeSecurity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Home phone.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_HomePhone() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_HomePhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Notes.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Info() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на IP phone.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_IpPhone() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_IpPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Location.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Location() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Location", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Mail.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Mail() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Mail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Manager.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Manager() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Manager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Member of.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_MemberOf() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_MemberOf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Members.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Members() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Members", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Mobile.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Mobile() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Mobile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Network.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Network() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Network", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Object.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Object() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Object", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Office.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_OfficeName() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_OfficeName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Operating system.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_OS() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_OS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Period.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Period() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Period", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Logon name (pre-Windows 2000).
        '''</summary>
        Public ReadOnly Property wndObject_lbl_SAMAccountName() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_SAMAccountName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Search.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Search() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Street address.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_StreetAddress() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_StreetAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Surname.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Surname() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Surname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Telephone number.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_TelephoneNumber() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_TelephoneNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Title.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Title() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Version.
        '''</summary>
        Public ReadOnly Property wndObject_lbl_Version() As String
            Get
                Return ResourceManager.GetString("wndObject_lbl_Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Login event log.
        '''</summary>
        Public ReadOnly Property wndObject_LoginEventLog() As String
            Get
                Return ResourceManager.GetString("wndObject_LoginEventLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Retrieving the login/logout events using WMI.
        '''</summary>
        Public ReadOnly Property wndObject_msg_RetrievingLoginsWMI() As String
            Get
                Return ResourceManager.GetString("wndObject_msg_RetrievingLoginsWMI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Account expires.
        '''</summary>
        Public ReadOnly Property wndObject_tt_AccountExpires() As String
            Get
                Return ResourceManager.GetString("wndObject_tt_AccountExpires", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Created.
        '''</summary>
        Public ReadOnly Property wndObject_tt_Created() As String
            Get
                Return ResourceManager.GetString("wndObject_tt_Created", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Last logon.
        '''</summary>
        Public ReadOnly Property wndObject_tt_LastLogon() As String
            Get
                Return ResourceManager.GetString("wndObject_tt_LastLogon", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
