'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ADToolsSIP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property phone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Default password is not set.
        '''</summary>
        Friend ReadOnly Property str_DefaultPasswordIsNotSet() As String
            Get
                Return ResourceManager.GetString("str_DefaultPasswordIsNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Disabled.
        '''</summary>
        Friend ReadOnly Property str_Disabled() As String
            Get
                Return ResourceManager.GetString("str_Disabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Enabled.
        '''</summary>
        Friend ReadOnly Property str_Enabled() As String
            Get
                Return ResourceManager.GetString("str_Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на expired.
        '''</summary>
        Friend ReadOnly Property str_Expired() As String
            Get
                Return ResourceManager.GetString("str_Expired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Account lockout duration.
        '''</summary>
        Friend ReadOnly Property str_LockoutDuration() As String
            Get
                Return ResourceManager.GetString("str_LockoutDuration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на {0} minutes.
        '''</summary>
        Friend ReadOnly Property str_LockoutDurationFormat() As String
            Get
                Return ResourceManager.GetString("str_LockoutDurationFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Reset account lockout counter after.
        '''</summary>
        Friend ReadOnly Property str_LockoutObservationWindow() As String
            Get
                Return ResourceManager.GetString("str_LockoutObservationWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на {0} minutes.
        '''</summary>
        Friend ReadOnly Property str_LockoutObservationWindowFormat() As String
            Get
                Return ResourceManager.GetString("str_LockoutObservationWindowFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Account lockout threshold.
        '''</summary>
        Friend ReadOnly Property str_LockoutThreshold() As String
            Get
                Return ResourceManager.GetString("str_LockoutThreshold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на {0} invalid logon attempts.
        '''</summary>
        Friend ReadOnly Property str_LockoutThresholdFormat() As String
            Get
                Return ResourceManager.GetString("str_LockoutThresholdFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Maximum password age.
        '''</summary>
        Friend ReadOnly Property str_MaximumPasswordAge() As String
            Get
                Return ResourceManager.GetString("str_MaximumPasswordAge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на {0} days.
        '''</summary>
        Friend ReadOnly Property str_MaximumPasswordAgeFormat() As String
            Get
                Return ResourceManager.GetString("str_MaximumPasswordAgeFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Minimum password age.
        '''</summary>
        Friend ReadOnly Property str_MinimumPasswordAge() As String
            Get
                Return ResourceManager.GetString("str_MinimumPasswordAge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на {0} days.
        '''</summary>
        Friend ReadOnly Property str_MinimumPasswordAgeFormat() As String
            Get
                Return ResourceManager.GetString("str_MinimumPasswordAgeFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Minimum password lenght.
        '''</summary>
        Friend ReadOnly Property str_MinimumPasswordLenght() As String
            Get
                Return ResourceManager.GetString("str_MinimumPasswordLenght", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на {0} characters.
        '''</summary>
        Friend ReadOnly Property str_MinimumPasswordLenghtFormat() As String
            Get
                Return ResourceManager.GetString("str_MinimumPasswordLenghtFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на never.
        '''</summary>
        Friend ReadOnly Property str_Never() As String
            Get
                Return ResourceManager.GetString("str_Never", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Object disabled.
        '''</summary>
        Friend ReadOnly Property str_ObjectDisabled() As String
            Get
                Return ResourceManager.GetString("str_ObjectDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Object expiration is unknown.
        '''</summary>
        Friend ReadOnly Property str_ObjectExpirationUnknown() As String
            Get
                Return ResourceManager.GetString("str_ObjectExpirationUnknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Object expired.
        '''</summary>
        Friend ReadOnly Property str_ObjectExpired() As String
            Get
                Return ResourceManager.GetString("str_ObjectExpired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Object status is unknown.
        '''</summary>
        Friend ReadOnly Property str_ObjectStatusUnknown() As String
            Get
                Return ResourceManager.GetString("str_ObjectStatusUnknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Password changed.
        '''</summary>
        Friend ReadOnly Property str_PasswordChanged() As String
            Get
                Return ResourceManager.GetString("str_PasswordChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Password must meet complexity requirements.
        '''</summary>
        Friend ReadOnly Property str_PasswordComplexityRequirements() As String
            Get
                Return ResourceManager.GetString("str_PasswordComplexityRequirements", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на {0}.
        '''</summary>
        Friend ReadOnly Property str_PasswordComplexityRequirementsFormat() As String
            Get
                Return ResourceManager.GetString("str_PasswordComplexityRequirementsFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Password expiration is unknown.
        '''</summary>
        Friend ReadOnly Property str_PasswordExpirationUnknown() As String
            Get
                Return ResourceManager.GetString("str_PasswordExpirationUnknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Password expired.
        '''</summary>
        Friend ReadOnly Property str_PasswordExpired() As String
            Get
                Return ResourceManager.GetString("str_PasswordExpired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Enforce password history.
        '''</summary>
        Friend ReadOnly Property str_PasswordHistory() As String
            Get
                Return ResourceManager.GetString("str_PasswordHistory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на {0} passwords remembered.
        '''</summary>
        Friend ReadOnly Property str_PasswordHistoryFormat() As String
            Get
                Return ResourceManager.GetString("str_PasswordHistoryFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на unknown.
        '''</summary>
        Friend ReadOnly Property str_Unknown() As String
            Get
                Return ResourceManager.GetString("str_Unknown", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
